baseURL = "https://excitonlabs.com"
languageCode = "en-us"
title = "Exciton Labs"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/exlabs_logo.png"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/exlabs_logo.png"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Exciton Labs"

  [params.homepage_meta_tags]
    meta_description = "Exciton Labs was founded in 2015 with the goal of rapidly delivering value to projects, large or small, for organisations ranging from individuals to multi-national corporations."
    meta_og_title = "Exciton Labs"
    meta_og_type = "website"
    meta_og_url = "https://excitonlabs.com"
    meta_og_image = "https://raw.githubusercontent.com/excitonlabs/website/master/static/favicon.png?token=GHSAT0AAAAAACQEDKAHDRSTLJYQ27Z5UEZMZTZEFGQ"
    meta_og_description = "Exciton Labs was founded in 2015 with the goal of rapidly delivering value to projects, large or small, for organisations ranging from individuals to multi-national corporations."

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
